// Generated by CoffeeScript 1.3.3
(function() {
  var TestWatchData, zookeeper, _zkClient;

  zookeeper = require('node-zookeeper-client');

  _zkClient = zookeeper.createClient("localhost:2181");

  _zkClient.connect();

  TestWatchData = function(client, path) {
    return client.getData(path, function(event) {
      console.log('Got event: %s.', event);
      return TestWatchData(client, path);
    }, function(err, data, stat) {
      if (err) {
        console.log("getData error:" + err.stack);
      }
      return console.log("Got data: %s", data != null ? data.toString('utf-8') : void 0);
    });
  };

  TestWatchData(_zkClient, '/eee/foo');

  TestWatchData(_zkClient, '/hades/configs/testProject');

}).call(this);
