// Generated by CoffeeScript 1.3.3
(function() {
  var LocalConfig, TEST_DATA_PATH;

  require("should");

  TEST_DATA_PATH = "/Users/vernonzheng/Project/github/hades-node-client/test/";

  LocalConfig = require("../src/module/config/local_config").LocalConfig;

  describe('test local config', function() {
    var config;
    config = LocalConfig.get("test", false);
    it('local config should have property - project', function() {
      return config.project.should.equal('testProject');
    });
    it('local config should have property - hostList', function() {
      return config.hostList.should.equal('localhost:2181');
    });
    it('local config should have property - retries', function() {
      return config.retries.should.equal(3);
    });
    return it('local config should have property - sessionTimeout', function() {
      return config.sessionTimeout.should.equal(60);
    });
  });

}).call(this);
