// Generated by CoffeeScript 1.3.3
(function() {
  var HOST, RemoteConfig, TEST_CONFIG, zkHelp;

  require("should");

  zkHelp = require("./zk_help");

  RemoteConfig = require("../src/module/config/remote_config").RemoteConfig;

  HOST = "127.0.0.1:2181";

  TEST_CONFIG = "TestRemoteConfig";

  describe('test remote static config', function() {
    var config;
    zkHelp.updateData("first data");
    config = RemoteConfig.get(TEST_CONFIG, false);
    return it('remote config - first data', function() {
      return config.should.equal("first data");
    });
  });

  describe('test remote dynamic config', function() {
    var dynamicConfig;
    zkHelp.updateData("first data");
    dynamicConfig = RemoteConfig.get(TEST_CONFIG, false);
    it('remote dynamic config should equal - first data', function() {
      return dynamicConfig.should.equal("first data");
    });
    return it('remote dyanmic config(when zk node changed) should equal - second data', function() {
      zkHelp.updateData("second data");
      return dynamicConfig.should.equal("second data");
    });
  });

}).call(this);
