// Generated by CoffeeScript 1.3.3
(function() {
  var updateData;

  updateData = function(data) {
    var client, zookeeper;
    zookeeper = require('node-zookeeper-client');
    client = zookeeper.createClient("127.0.0.1:2181", {
      retries: 3,
      sessionTimeout: 10000
    });
    return client.setData("/hades/configs/testProject/TestRemoteConfig", new Buffer(data, "utf-8"), 1, function(err, stat) {
      if (err) {
        return console.log("set data error:" + err.stack);
      }
    });
  };

  updateData(33333);

  exports.updateData = updateData;

}).call(this);
