// Generated by CoffeeScript 1.3.3
(function() {
  var IConfig, Module,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Module = require("../../lib/Module");

  IConfig = (function(_super) {

    __extends(IConfig, _super);

    function IConfig() {
      return IConfig.__super__.constructor.apply(this, arguments);
    }

    IConfig.prototype.get = function(name) {};

    IConfig.prototype.getDynamic = function(name) {};

    return IConfig;

  })(Module);

  exports.IConfig = IConfig;

}).call(this);
