// Generated by CoffeeScript 1.3.3
(function() {
  var IConfig, Module,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Module = require("../../lib/Module");

  IConfig = (function(_super) {
    var IS_DYNAMIC, IS_STATIC, get, load;

    __extends(IConfig, _super);

    /*
    		static pool
    */


    function IConfig() {
      return IConfig.__super__.constructor.apply(this, arguments);
    }

    IS_DYNAMIC = true;

    IS_STATIC = false;

    /*
    	    load config
    */


    load = function() {};

    /*
    	    fetch config
    	    @param name : config name，unique
    	    @param isDynamic :
    	        {true:dynamic（only support remote config） false:static}
    */


    get = function(name, isDynamic) {};

    return IConfig;

  })(Module);

  exports.IConfig = IConfig;

}).call(this);
